spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/SpringCloud_Sell?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
  #默认自动配置了的
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: 127.0.0.1
env: test
girl: 
  name: feifei
  age: 18
